parameters:
#    don_car_pdi.example.class: DonCar\PDIBundle\Example

services:
#    don_car_pdi.example:
#        class: %don_car_pdi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
